// <auto-generated />
using AppDataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppModel.Models.Depolar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CALISANSAYISI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Depolars");
                });

            modelBuilder.Entity("AppModel.Models.Musteriler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOYADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Musterilers");
                });

            modelBuilder.Entity("AppModel.Models.Urunler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ALISFIYAT")
                        .HasColumnType("int");

                    b.Property<string>("MARKA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SATISFIYAT")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
